### ISSUE TITLE
"Failed to load the API!" when opening the Guide Book

### ISSUE THREAD

**Issue by VikeStep** [LatvianModder/FTBGuides#7]
Repro Steps:
1. Download FTB Pyramid Reborn
2. Create a new world using the provided map
3. Try open the Guide Book (doesn't matter if through book, NEI button, or pressing G)

Expected: Guide Book opens
Actual: 
- Loading icon appears then nothing is displayed.
- `[ReloadGuides/ERROR] [FTB Guides]: Failed to load the API!` appears in the log
- The screen is frozen until escape is pressed
- Once back in main game, all further attempts to open the guide book cause it to instantly freeze without the loading icon. The log does not appear on further attempts

Other Info:
- Looks like the line of code throwing the error is [here](https://github.com/LatvianModder/FTBGuides/blob/master/src/main/java/com/feed_the_beast/ftbguides/client/ThreadLoadGuides.java#L195). 
- I can't seem to see any other stacktraces in the log file relating to this so I don't believe an exception is thrown when it calls `DataReader.get` a few lines above it.
- Accessing the [API Json](https://guides.latmod.com/api/api.json) directly returns me a valid JSON
- Perhaps the error might be in FTBLib, but I wasn't certain
- Versions:
  - FTBLib 5.0.0.14
  - FTB Guides 1.0.0.12
  - Forge 14.23.2.2632
  - Java 1.8.0_121
- [Log file](https://gist.github.com/VikeStep/fe02c680df858781912f8519d9dfc2c1)
- Looks like I'm [not the only one with this issue](https://forum.feed-the-beast.com/threads/guide-book-not-working.277606)

**Comment by Excyclic** [comment]
It appears the url in the code on line 186 in com.feed_the_beast.ftbguides.client.ThreadLoadGuides needs to be changed.  The current url in the code **http://guides.latmod.com/api/api.json** redirects to **https://guides.latmod.com/api/api.json** and the URL.openConnection method does not handle redirection automatically causing the failure.

**Comment by Lavasyris** [comment]
I am having the same issue. If the cause of the problem is the same for me, how exactly do I fix that?

**Comment by LatvianModder** [comment]
You can't fix it, next update of FTB Guides will fix it

**Comment by rgeorgeoff** [comment]
Also waiting :)

**Comment by DeividasX** [comment]
Having the same issue on latest FTB Pyramid Reborn

**Comment by Darkmift** [comment]
Its a shame this issue sounds somewhat simple to fix and yet its a major bug.
Hope it gets addressed soon.

**Comment by LatvianModder** [comment]
It's been fixed for weeks 🤔 
Not my problem packs aren't updating

**Comment by Darkmift** [comment]
You're right,
Digging into the jar associated with the pack indicates failure to retrieve from local directory but also said dir is missing a giant portion of data.

Hope ftb address this soon but seems someone caused a big mess.

**Comment by Airova** [comment]
I'm also having this issue in the current version of the pack. Asking around to see if it's everyone or just an unlucky portion of us... I really hope they fix this soon. :(

**Comment by varadinn** [comment]
ok so I'm not the only one having this issue lol thought it was just me. I cant open any books in any way

**Comment by yerkish** [comment]
something I'm going to try is downloading the most recent FTBGuides to the mod list for FTB. I'll be following my path "...\ftb\FTBPyramidReborn\minecraft\mods" and deleting my FTBGuides file, and I'll replace it with the most recent one. Wish me luck.

**Comment by LatvianModder** [comment]
You cant update just guides, you also need to update ftblib, ftbutilities and yabba

**Comment by ET-Bent** [comment]
Any news on this one?

**Comment by LatvianModder** [comment]
The bug has been fixed forever ago

**Comment by Zodsmar** [comment]
I seem to still get the same issue on FTB Pyramid. I can't open guide at all.

**Comment by jheiv** [comment]
@LatvianModder I'm not sure it has been.  Pulled from curse today: `[10:27:06] [ReloadGuides/ERROR] [FTB Guides]: Failed to load the API!`
